vich_uploader:
    db_driver: orm

    mappings:
        membres:
            uri_prefix: '%app.path.membres%'
            upload_destination: '%kernel.project_dir%/../assets/uploads/images/membres'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        micropousses:
            uri_prefix: '%app.path.micropousses%'
            upload_destination: '%kernel.project_dir%/../public/uploads/images/micropousses'
            namer: Vich\UploaderBundle\Naming\OrignameNamer


        recettes:
            uri_prefix: '%app.path.recettes%'
            upload_destination: '%kernel.project_dir%/../public/uploads/images/recettes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true