#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: '../src/Controller/'
    type:     annotation

backend:
    resource: '../src/Controller/AdminController.php'
    prefix: /admin
    type: annotation