<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MKbV4_g' shared service.

return $this->privates['.service_locator.MKbV4_g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ContactController::index' => ['privates', '.service_locator.y64njkX', 'get_ServiceLocator_Y64njkXService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\ContactController:index' => ['privates', '.service_locator.y64njkX', 'get_ServiceLocator_Y64njkXService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\ContactController::index' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\ContactController:index' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
