<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\AdminController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Controller/EasyAdminController.php';
include_once $this->targetDirs[3].'/src/Controller/AdminController.php';

$this->services['App\\Controller\\AdminController'] = $instance = new \App\Controller\AdminController(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));

$instance->setContainer(($this->privates['.service_locator.gGTGrJ1'] ?? $this->load('get_ServiceLocator_GGTGrJ1Service.php'))->withContext('App\\Controller\\AdminController', $this));

return $instance;
