<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Notification\ContactNotification' shared autowired service.

include_once $this->targetDirs[3].'/src/Notification/ContactNotification.php';

return $this->privates['App\\Notification\\ContactNotification'] = new \App\Notification\ContactNotification(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['twig'] ?? $this->getTwigService()));
