<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'easyadmin.command.make_admin_migration' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Command/MakeAdminMigrationCommand.php';

$this->services['easyadmin.command.make_admin_migration'] = $instance = new \EasyCorp\Bundle\EasyAdminBundle\Command\MakeAdminMigrationCommand(($this->services['easyadmin.config.manager'] ?? $this->getEasyadmin_Config_ManagerService()), $this->targetDirs[3]);

$instance->setName('make:admin:migration');

return $instance;
