<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZY5JXP0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZY5JXP0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZY5JXP0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZY5JXP0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZY5JXP0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZY5JXP0',
    'container.build_id' => '929945a9',
    'container.build_time' => 1588608706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZY5JXP0');
