<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\AdminController::indexAction'], [], [['text', '/admin/']], [], []],
    'contact' => [['nameEntreprise'], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact'], ['variable', '/', '[^/]++', 'nameEntreprise', true]], [], []],
    'content' => [[], ['_controller' => 'App\\Controller\\ContentController::index'], [], [['text', '/content']], [], []],
    'footer' => [[], ['_controller' => 'App\\Controller\\FooterController::index'], [], [['text', '/footer']], [], []],
    'page' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/page']], [], []],
    'home_page' => [[], ['_controller' => 'App\\Controller\\PageController::homePage'], [], [['text', '/']], [], []],
    'home_ville' => [['nameEntreprise'], ['_controller' => 'App\\Controller\\PageController::homeVillePage'], [], [['text', '/accueil'], ['variable', '/', '[^/]++', 'nameEntreprise', true]], [], []],
    'nos_missions' => [['nameEntreprise'], ['_controller' => 'App\\Controller\\PageController::missionPage'], [], [['text', '/nos-animations'], ['variable', '/', '[^/]++', 'nameEntreprise', true]], [], []],
    'nos_micropousses' => [['nameEntreprise'], ['_controller' => 'App\\Controller\\PageController::micropoussePage'], [], [['text', '/nos-micro-pousses'], ['variable', '/', '[^/]++', 'nameEntreprise', true]], [], []],
    'notOnline' => [[], ['_controller' => 'App\\Controller\\PageController::notOnline'], [], [['text', '/sorry']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/register']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/loginAdmin']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::indexAction'], [], [['text', '/admin/easyadmin/']], [], []],
];
